# NumPy Basics

## Aim

The aim of this notebook is to understand the basic operations of the NumPy library. The notebook demonstrates how to create one-dimensional, two-dimensional, and three-dimensional arrays, perform matrix addition and multiplication, calculate statistical measures such as mean and standard deviation, and reshape arrays.

In [1]:
import numpy as np

# Creating NumPy Arrays

NumPy provides the `array()` function to create arrays of different dimensions. Arrays are faster and more efficient than Python lists for numerical computations.

In [2]:
# One Dimensional Array
arr = np.array([10, 20, 30, 40, 50])

print("One Dimensional Array:")
print(arr)

# Two Dimensional Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\nTwo Dimensional Array:")
print(arr2)

# Three Dimensional Array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("\nThree Dimensional Array:")
print(arr3)

One Dimensional Array:
[10 20 30 40 50]

Two Dimensional Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Three Dimensional Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Explanation

- A **1D array** stores elements in a single row.
- A **2D array** stores data in rows and columns, similar to a matrix.
- A **3D array** stores multiple 2D arrays, often used in image processing and scientific computing.
# Matrix Addition

Matrix addition is performed by adding corresponding elements of two matrices having the same dimensions.

In [3]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Using + operator
C = A + B

print("Matrix Addition using +")
print(C)

# Using NumPy add()
D = np.add(A, B)

print("\nMatrix Addition using np.add()")
print(D)

Matrix Addition using +
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix Addition using np.add()
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Explanation

Two matrices can be added only if they have the same dimensions. NumPy provides two methods for addition:

- Using the `+` operator.
- Using the `np.add()` function.
# Matrix Multiplication

Matrix multiplication combines two matrices to produce another matrix. The number of columns in the first matrix must be equal to the number of rows in the second matrix.

In [4]:
# First Matrix (2 × 3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Second Matrix (3 × 2)
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# Matrix Multiplication
C = A @ B

print("Product of Matrices:")
print(C)

Product of Matrices:
[[ 58  64]
 [139 154]]


### Explanation

The `@` operator performs matrix multiplication. It multiplies rows of the first matrix with columns of the second matrix to generate the result.
# Mean and Standard Deviation

Mean represents the average value of the elements, while standard deviation measures how much the values vary from the mean.

In [5]:
arr = np.array([10, 20, 30, 40, 50, 60])

mean = np.mean(arr)
std = np.std(arr)

print("Array:", arr)
print("Mean:", mean)
print("Standard Deviation:", std)

Array: [10 20 30 40 50 60]
Mean: 35.0
Standard Deviation: 17.07825127659933


### Explanation

- `np.mean()` calculates the arithmetic mean.
- `np.std()` calculates the standard deviation, which indicates the spread of the data.
# Reshaping an Array

The `reshape()` function changes the shape of an array without changing its data.

In [6]:
new_arr = arr.reshape(2, 3)

print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(new_arr)

Original Array:
[10 20 30 40 50 60]

Reshaped Array:
[[10 20 30]
 [40 50 60]]


### Explanation

The original one-dimensional array containing six elements is reshaped into a **2 × 3** matrix. The total number of elements remains the same.
# Conclusion

In this notebook, the fundamental operations of the NumPy library were demonstrated. Arrays of different dimensions were created, matrix addition and multiplication were performed, statistical functions such as mean and standard deviation were calculated, and arrays were reshaped. These operations form the foundation for numerical computing, scientific applications, and machine learning using Python.