# NumPy Random Matrices and Matrix Operations

## Aim

The aim of this notebook is to learn how to generate random matrices using NumPy and Python's `random` module, calculate row-wise and column-wise sums and means, and perform matrix transposition. These operations are fundamental in data analysis, linear algebra, and machine learning.

In [1]:
import numpy as np
import random as rnd

# Generating Random Matrices

Random matrices are useful for testing algorithms, simulations, and performing mathematical computations. In this section, random matrices are generated using both NumPy and Python's built-in `random` module.

In [2]:
# Random Matrix using NumPy

random_matrix = np.random.randint(1, 100, size=(3,3))

# Random Matrix using Python's random module

random_matrix2 = np.array([
    [rnd.randint(0,10) for j in range(3)]
    for i in range(3)
])

print("Random Matrix using NumPy")
print(random_matrix)

print("\nRandom Matrix using random module")
print(random_matrix2)

Random Matrix using NumPy
[[72 13 96]
 [67 99 82]
 [ 3  7 60]]

Random Matrix using random module
[[ 9  2  6]
 [ 9  2  8]
 [ 8  6 10]]


### Explanation

- `np.random.randint()` generates random integers within a specified range.
- `size=(3,3)` creates a matrix with 3 rows and 3 columns.
- The second matrix is created using Python's `random.randint()` inside a nested list comprehension and then converted into a NumPy array.
# Row Sum and Column Sum

NumPy allows easy computation of row-wise and column-wise sums using the `sum()` function with the `axis` parameter.

In [3]:
matrix_1 = np.random.randint(1,100,size=(4,4))

print("Matrix")
print(matrix_1)

column_sum = matrix_1.sum(axis=0)

row_sum = matrix_1.sum(axis=1)

print("\nColumn Sum")
print(column_sum)

print("\nRow Sum")
print(row_sum)

Matrix
[[86 50 94 89]
 [ 5 10  7 18]
 [18 60 38 49]
 [63  1 20 45]]

Column Sum
[172 121 159 201]

Row Sum
[319  40 165 129]


### Explanation

- `axis=0` calculates the sum of each column.
- `axis=1` calculates the sum of each row.
- NumPy performs these calculations efficiently without using loops.
# Row Mean and Column Mean

The average value of each row and column is calculated using the `mean()` function.

In [4]:
mean_col = np.mean(matrix_1, axis=0)

mean_row = np.mean(matrix_1, axis=1, keepdims=True)

print("Mean Along Columns")
print(mean_col)

print("\nMean Along Rows")
print(mean_row)

Mean Along Columns
[43.   30.25 39.75 50.25]

Mean Along Rows
[[79.75]
 [10.  ]
 [41.25]
 [32.25]]


### Explanation

- `axis=0` computes the mean of each column.
- `axis=1` computes the mean of each row.
- `keepdims=True` preserves the original two-dimensional structure by keeping the result as a column vector.
# Matrix Transpose

The transpose of a matrix is obtained by interchanging its rows and columns.

In [5]:
original_matrix = np.random.randint(1,100,size=(4,3))

print("Original Matrix")
print(original_matrix)

transposed_matrix = original_matrix.transpose()

transposed_matrix2 = np.transpose(original_matrix)

print("\nTranspose using transpose()")
print(transposed_matrix)

print("\nTranspose using np.transpose()")
print(transposed_matrix2)

Original Matrix
[[57 32 86]
 [10  6 51]
 [40 74 30]
 [36 80 15]]

Transpose using transpose()
[[57 10 40 36]
 [32  6 74 80]
 [86 51 30 15]]

Transpose using np.transpose()
[[57 10 40 36]
 [32  6 74 80]
 [86 51 30 15]]


### Explanation

- `transpose()` swaps the rows and columns of a matrix.
- `np.transpose()` performs the same operation as the `transpose()` method.
- If the original matrix has dimensions **4 × 3**, the transposed matrix will have dimensions **3 × 4**.
# Conclusion

In this notebook, random matrices were generated using both NumPy and Python's `random` module. Row-wise and column-wise sums and means were calculated using NumPy's built-in functions. Finally, matrix transposition was performed using two different methods. These operations demonstrate the efficiency and simplicity of NumPy for numerical computations and form an essential foundation for data science, machine learning, and scientific computing.